Update actions.yml

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -1,36 +1,33 @@
-name: Run runreport.py
+name: run runreport.py
 
 on:
-  workflow_dispatch:
+  schedule:
+    - cron: '* * * * *' # At every minute
 
 jobs:
-  run_process_stock_data:
+  build:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout repository content
-        uses: actions/checkout@v3
 
-      - name: Set up Python
+      - name: checkout repo content
+        uses: actions/checkout@v3 # checkout the repository content to github runner
+
+      - name: setup python
         uses: actions/setup-python@v4
         with:
-          python-version: '3.11'
+          python-version: '3.11' # install the python version needed
           
-      - name: Install Python packages
+      - name: install python packages
         run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt
       
       - name: Run process_stock_data function
-        run: |
-          python -c "
-import sys
-from BackEnd.runreport import process_stock_data
-from datetime import datetime
+        run: python -c "from Backend.runreport import process_stock_data; from datetime import datetime; process_stock_data(datetime.now())"
 
-try:
-    process_stock_data(datetime.now())
-    print('Process completed successfully.')
-except Exception as e:
-    print(f'An error occurred: {e}')
-    sys.exit(1)
-          "
+      - name: Check output
+        run: |
+          if [ $? -ne 0 ]; then
+            echo "The previous command failed!"
+            exit 1
+          fi
